stages:
 - test
 - build
 - dist
 - release

variables:
  CONTAINER_TEST_IMAGE: tracker.parsys.com:1337/parsys/asset_tracker:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: tracker.parsys.com:1337/parsys/asset_tracker:latest

flake8:
  stage: test
  image: python:3.5
  tags:
    - docker

  script:
    - pip install -q -U pip setuptools wheel
    - pip -q install '.[qa]'
    - flake8

build:
  stage: build
  image: python:3.5
  tags:
    - docker

  script:
    - pip -q install -U pip wheel setuptools
    - python setup.py bdist_wheel
    - pip wheel -w dist/ '.[prod]'

  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    expire_in: 6 hours
    paths:
      - dist/

docker-image:
  stage: dist
  tags:
    - docker-builder

  script:
    - echo creating $CONTAINER_TEST_IMAGE
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN tracker.parsys.com:1337
    - docker push $CONTAINER_TEST_IMAGE

release-image:
  stage: release
  tags:
    - docker-builder

  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN tracker.parsys.com:1337
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master


# TODO : run tests
