stages:
  - test
  - build
  - dist
  - release
  - deploy

variables:
  CONTAINER_TEST_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_BUILD_REF_NAME}
  CONTAINER_RELEASE_IMAGE: ${CI_REGISTRY_IMAGE}:latest
  GITLAB_INDEX_URL: https://gitlab-ci-token:${CI_JOB_TOKEN}@tracker.parsys.com/api/v4/projects/9/packages/pypi/simple
  PIP_CACHE_DIR: ${CI_PROJECT_DIR}/.cache/pip

flake8:
  stage: test
  image: python:3.8
  tags:
    - docker
    - asset_tracker

  cache:
    key: ${CI_PROJECT_ID}
    paths:
      - .cache/pip

  script:
    - pip3 install -q -U pip setuptools wheel
    - pip3 install -q --extra-index-url ${GITLAB_INDEX_URL} '.[qa]'
    - flake8

pytest:
  stage: test
  image: python:3.8
  tags:
    - docker
    - asset_tracker

  cache:
    key: ${CI_PROJECT_ID}
    paths:
      - .cache/pip
    policy: pull

  script:
    - pip3 install -q -U pip setuptools wheel
    - pip3 install -q --extra-index-url ${GITLAB_INDEX_URL} '.[tests]'
    - py.test --cov=asset_tracker

build:
  stage: build
  image: python:3.8
  tags:
    - docker
    - asset_tracker

  cache:
    key: ${CI_PROJECT_ID}
    paths:
      - .cache/pip
    policy: pull

  script:
    - pip3 install -q -U pip setuptools wheel
    - python3 setup.py bdist_wheel
    - pip3 wheel -w dist/ --extra-index-url ${GITLAB_INDEX_URL} .

  artifacts:
    name: ${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}
    expire_in: 6 hours
    paths:
      - dist/

docker-image:
  stage: dist
  tags:
    - shell

  script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker build -t ${CONTAINER_TEST_IMAGE} .

release-image:
  stage: release
  tags:
    - shell

  script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker push ${CONTAINER_TEST_IMAGE}

release-latest-image:
  stage: release
  tags:
    - shell
  only:
    - master

  script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker tag ${CONTAINER_TEST_IMAGE} ${CONTAINER_RELEASE_IMAGE}
    - docker push ${CONTAINER_RELEASE_IMAGE}

deploy_dev:
  stage: deploy
  tags:
    - shell
  only:
    - develop

  script:
    - ssh root@at.dev.parsys.com parsys upgrade at.dev.parsys.com

  environment:
    name: dev
    url: https://at.dev.parsys.com

deploy_staging:
  stage: deploy
  tags:
    - shell
  only:
    - master

  script:
    - ssh root@at.cloud.staging.parsys.com parsys upgrade at.cloud.staging.parsys.com

  environment:
    name: staging
    url: https://at.cloud.staging.parsys.com

deploy_staging_marlink:
  stage: deploy
  tags:
    - shell
  only:
    - master

  script:
    - ssh root@asset.pp.telemed.marlink.com parsys upgrade asset.pp.telemed.marlink.com

  environment:
    name: staging_marlink
    url: https://asset.pp.telemed.marlink.com
