[build-system]
requires = [
    'setuptools==69.0.2',
    'setuptools-scm==8.0.4',
    'wheel==0.41.2',
]
build-backend = 'setuptools.build_meta'

[project]
name = 'asset-tracker'
description = 'Asset Tracker'
requires-python = '>=3.10'
keywords = ['web', 'pyramid', 'pylons']
authors = [
  {email = 'info@parsys.com'},
  {name = 'Parsys'},
]
license = {text = 'Other/Proprietary License'}
classifiers = [
    'Framework :: Pyramid',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Topic :: Internet :: WWW/HTTP',
    'Topic :: Internet :: WWW/HTTP :: WSGI :: Application',
]
dependencies = [
    'alembic==1.12.1',
    'celery[redis]==5.3.6',
    'filedepot==0.10.0',
    'jinja2==3.1.2',
    'packaging==23.2',
    'parsys-utilities~=4.8.0',
    'paste==3.7.1',
    'psycopg2==2.9.9',
    'pyramid==1.10.8',
    'pyramid-jinja2==2.10.0',
    'pyramid-session-redis==1.6.3',
    'pyramid-tm==2.5',
    'python-dateutil==2.8.2',
    'sentry-sdk==1.36.0',
    'sqlalchemy==1.4.50',
    'transaction==4.0',
    'waitress==2.1.2',
    'zope.sqlalchemy==3.1',
]
dynamic = ['readme', 'version']

[project.optional-dependencies]
dev = [
    'babel==2.13.1',
    'pybabel-json-md==0.1.0',
    'pyramid-debugtoolbar==4.10',
]
qa = [
    'flake8==6.1.0',
    'flake8-pyproject==1.2.3',
]
tests = [
    'parsys-utilities[tests]~=4.7.8',
    'pytest==7.4.3',
    'pytest-cov==4.1.0',
]

[project.urls]
homepage = 'https://parsys.com'

[project.entry-points.'paste.app_factory']
main = 'asset_tracker:main'

[project.scripts]
parsys_healthcheck = 'parsys_utilities.status:healthcheck'

[tool.flake8]
doctests = true
max-line-length = 120
statistics = true

[tool.setuptools.dynamic]
readme = {file = ['README.md', 'CHANGES.md']}

[tool.setuptools.packages.find]
include = ['asset_tracker*']
exclude = ['asset_tracker.js*', 'asset_tracker.sass*', 'asset_tracker.scripts*', 'asset_tracker.tests*']

[tool.setuptools.exclude-package-data]
'*' = ['*.ejs', '*.ini', '*.po', '*.pot', '*.sh']
'asset_tracker' = ['js*', 'sass*', 'scripts*', 'tests*']

[tool.setuptools_scm]
version_scheme = 'no-guess-dev'
