[build-system]
requires = [
    'setuptools==67.6.1',
    'setuptools-scm==7.1.0',
    'wheel==0.40.0',
]
build-backend = 'setuptools.build_meta'

[project]
name = 'asset-tracker'
description = 'Asset Tracker'
requires-python = '>=3.10'
keywords = ['web', 'pyramid', 'pylons']
authors = [
  {email = 'info@parsys.com'},
  {name = 'Parsys'},
]
license = {text = 'Other/Proprietary License'}
classifiers = [
    'Framework :: Pyramid',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Topic :: Internet :: WWW/HTTP',
    'Topic :: Internet :: WWW/HTTP :: WSGI :: Application',
]
dependencies = [
    'alembic==1.10.1',
    'celery[redis]==5.2.7',
    'filedepot==0.9.0',
    'jinja2==3.1.2',
    'packaging==23.0',
    'parsys-utilities==4.6.4',
    'paste==3.5.2',
    'psycopg2==2.9.6',
    'pyramid==1.10.8',
    'pyramid-jinja2==2.10.0',
    'pyramid-session-redis==1.6.3',
    'pyramid-tm==2.5',
    'python-dateutil==2.8.2',
    'sentry-sdk==1.16.0',
    'sqlalchemy==1.4.46',
    'transaction==3.0.1',
    'waitress==2.1.2',
    'zope.sqlalchemy==2.0',
]
dynamic = ['readme', 'version']

[project.optional-dependencies]
dev = [
    'babel==2.12.1',
    'pybabel-json-md==0.1.0',
    'pyramid-debugtoolbar==4.10',
]
qa = ['flake8==6.0.0']
tests = [
    'pytest==7.3.1',
    'pytest-cov==4.0.0',
    'webtest==3.0.0',
]

[project.urls]
homepage = 'https://parsys.com'

[project.entry-points.'paste.app_factory']
main = 'asset_tracker:main'

[project.scripts]
parsys_healthcheck = 'parsys_utilities.status:healthcheck'

[tool.setuptools.dynamic]
readme = {file = ['README.md', 'CHANGES.md']}

[tool.setuptools.packages.find]
include = ['asset_tracker*']
exclude = ['asset_tracker.tests*']

[tool.setuptools_scm]
